import { app, BrowserWindow, ipcMain } from 'electron';
import keytar from 'keytar';
import {
  loginRequest,
  addLabProcessorInput,
  listLabProcessorInputs,
  listPendingLabProcessorInputs,
  updateLabProcessorInput,
  type LabProcessorInputPayload,
  type LabProcessorInputUpdatePayload,
} from './main/api';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// Constants
const AUTH_SERVICE = 'herblink-lab-app';
const AUTH_ACCOUNT = 'lab-user';

// Function to register all IPC handlers
const registerIpcHandlers = () => {
  // Remove existing handlers first to avoid duplicate registration errors
  try {
    ipcMain.removeHandler('auth:login');
  } catch (e) {
    // Handler doesn't exist, that's fine
  }

  try {
    ipcMain.removeHandler('lab:addProcessorInput');
  } catch (e) {
    // Handler doesn't exist, that's fine
  }

  try {
    ipcMain.removeHandler('lab:listProcessorInputs');
  } catch (e) {
    // Handler doesn't exist, that's fine
  }

  try {
    ipcMain.removeHandler('lab:listPendingProcessorInputs');
  } catch (e) {
    // Handler doesn't exist, that's fine
  }

  try {
    ipcMain.removeHandler('lab:updateProcessorInput');
  } catch (e) {
    // Handler doesn't exist, that's fine
  }

  // Auth handler
  ipcMain.handle(
    'auth:login',
    async (_event, credentials: { email?: string; password?: string }) => {
      const email = credentials?.email?.trim();
      const password = credentials?.password;

      if (!email || !password) {
        return { success: false, error: 'Email and password are required.' };
      }

      try {
        const { token } = await loginRequest({ email, password });
        await keytar.setPassword(AUTH_SERVICE, AUTH_ACCOUNT, token);
        return { success: true };
      } catch (error) {
        const message =
          error instanceof Error ? error.message : 'Unexpected login error.';
        return { success: false, error: message };
      }
    }
  );

  // Lab Processor Input IPC Handlers
  ipcMain.handle(
    'lab:addProcessorInput',
    async (_event, payload: LabProcessorInputPayload) => {
      try {
        const result = await addLabProcessorInput(payload);
        if (result.error === 'UNAUTHORIZED') {
          // Clear token and return error
          await keytar.deletePassword(AUTH_SERVICE, AUTH_ACCOUNT);
          return { ...result, logout: true };
        }
        return result;
      } catch (error) {
        return {
          data: null,
          error: error instanceof Error ? error.message : 'Unexpected error occurred.',
        };
      }
    }
  );

  ipcMain.handle('lab:listProcessorInputs', async () => {
    try {
      const result = await listLabProcessorInputs();
      if (result.error === 'UNAUTHORIZED') {
        await keytar.deletePassword(AUTH_SERVICE, AUTH_ACCOUNT);
        return { ...result, logout: true };
      }
      return result;
    } catch (error) {
      return {
        data: null,
        error: error instanceof Error ? error.message : 'Unexpected error occurred.',
      };
    }
  });

  ipcMain.handle('lab:listPendingProcessorInputs', async () => {
    try {
      const result = await listPendingLabProcessorInputs();
      if (result.error === 'UNAUTHORIZED') {
        await keytar.deletePassword(AUTH_SERVICE, AUTH_ACCOUNT);
        return { ...result, logout: true };
      }
      return result;
    } catch (error) {
      return {
        data: null,
        error: error instanceof Error ? error.message : 'Unexpected error occurred.',
      };
    }
  });

  ipcMain.handle(
    'lab:updateProcessorInput',
    async (_event, id: string, payload: LabProcessorInputUpdatePayload) => {
      try {
        const result = await updateLabProcessorInput(id, payload);
        if (result.error === 'UNAUTHORIZED') {
          await keytar.deletePassword(AUTH_SERVICE, AUTH_ACCOUNT);
          return { ...result, logout: true };
        }
        return result;
      } catch (error) {
        return {
          data: null,
          error: error instanceof Error ? error.message : 'Unexpected error occurred.',
        };
      }
    }
  );
};

// Register handlers once when module loads
registerIpcHandlers();

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
